# inspired at https://github.com/phpstan/extension-installer/blob/master/.github/workflows/integration-tests.yml
name: e2e Tests

on: [push, pull_request]

defaults:
    run:
        # important location of script runs bellow!
        working-directory: e2e/upgrade-package

jobs:
    e2e_tests:
        runs-on: ubuntu-latest

        steps:
            -
                uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0

            # locks to provided Symfony 5.0.*
            -   run: composer update --no-interaction --no-progress --ansi

            # new package → should invoke update of package even
            -   run: composer require symfony/console 6.0 --ansi
