name: PHP Linter

on: [push, pull_request]

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    php_linter:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.1
                    coverage: none

            -
                run: composer create-project php-parallel-lint/php-parallel-lint php-parallel-lint
            -
                run: php php-parallel-lint src tests
